// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPProject.Models
{
    [Table("OrderLineItem")]
    public partial class OrderLineItem
    {
        [Key]
        public int LineItemID { get; set; }
        public int Quantity { get; set; }
        public int? ProductID { get; set; }
        public int? OrderID { get; set; }

        [ForeignKey("OrderID")]
        [InverseProperty("OrderLineItems")]
        public virtual Order Order { get; set; }
        [ForeignKey("ProductID")]
        [InverseProperty("OrderLineItems")]
        public virtual Product Product { get; set; }
    }
}