// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPProject.Models
{
    [Table("Product")]
    public partial class Product
    {
        public Product()
        {
            OrderLineItems = new HashSet<OrderLineItem>();
        }

        [Key]
        public int ProductID { get; set; }
        [StringLength(50)]
        public string ProductName { get; set; }
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }
        public int ModelNumber { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Thumbnail { get; set; }
        public int? ProductTypeID { get; set; }

        [ForeignKey("ProductTypeID")]
        [InverseProperty("Products")]
        public virtual ProductType ProductType { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
    }
}