// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ASPProject.Models
{
    [Table("ProductType")]
    public partial class ProductType
    {
        public ProductType()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int ProductTypeID { get; set; }
        [StringLength(50)]
        public string ProductTypeName { get; set; }
        [StringLength(50)]
        public string ProductTypeDescription { get; set; }
        [StringLength(50)]
        public string ProductTypeImage { get; set; }

        [InverseProperty("ProductType")]
        public virtual ICollection<Product> Products { get; set; }
    }
}